services:
  upgrade-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./djangifylab_project:/app/djangifylab_project
      - ./example-apps/packages:/app/packages
      - ./example-apps/fixtures:/app/fixtures
      - ./upgrade_logs:/app/logs
    environment:
      - DB=postgres
    command: >
      python entrypoint.py
      --mode upgrade
      --previous_version /app/packages/buffalogs-2.7.0.tar.gz
      --new_version /app/packages/buffalogs-2.8.0.tar.gz
      --fixture /app/fixtures/buffalogs_complete_fixture.json
      --db postgres
    depends_on:
      - postgres
    networks:
      - djangifylab_network

  app-installer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example-apps/packages:/app/packages
    command: python entrypoint.py --mode install --target /app/packages
    depends_on:
      - postgres
    networks:
      - djangifylab_network

networks:
  djangifylab_network:
    driver: bridge
