name: Deploy on Version PR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'develop' &&
      github.event.pull_request.title =~ '^\d+\.\d+\.\d+$'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Extract version from PR title
        id: version
        run: |
          echo "::set-output name=tag::v${{ github.event.pull_request.title }}"

      - name: Create Git Tag
        run: |
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}